"""initial

Revision ID: 70aac81f525f
Revises: 
Create Date: 2026-01-28 20:34:24.004415

"""
from typing import Sequence, Union


from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = '70aac81f525f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')


    op.execute('CREATE SCHEMA IF NOT EXISTS analysis')
    op.execute('CREATE SCHEMA IF NOT EXISTS files')
    op.execute('CREATE SCHEMA IF NOT EXISTS knowledge')
    op.execute('CREATE SCHEMA IF NOT EXISTS users')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='analysis'
    )
    op.create_table('comparison_row',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('analysis_id', sa.UUID(), nullable=False),
    sa.Column('characteristic', sa.String(), nullable=False),
    sa.Column('tz_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('passport_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('llm_result', sa.Boolean(), nullable=True),
    sa.Column('user_result', sa.Boolean(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='analysis'
    )
    op.create_table('user_edit',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('comparison_row_id', sa.UUID(), nullable=False),
    sa.Column('old_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('edited_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='analysis'
    )
    op.create_table('file',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('analysis_id', sa.UUID(), nullable=False),
    sa.Column('file_type', sa.String(), nullable=False),
    sa.Column('original_name', sa.String(), nullable=False),
    sa.Column('storage_path', sa.String(), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='files'
    )
    op.create_table('knowledge_entry',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='knowledge'
    )
    op.create_table('user',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('login', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login'),
    schema='users'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user', schema='users')
    op.drop_table('knowledge_entry', schema='knowledge')
    op.drop_table('file', schema='files')
    op.drop_table('user_edit', schema='analysis')
    op.drop_table('comparison_row', schema='analysis')
    op.drop_table('analysis', schema='analysis')
    # ### end Alembic commands ###
    op.execute('DROP SCHEMA IF EXISTS users CASCADE')
    op.execute('DROP SCHEMA IF EXISTS knowledge CASCADE')
    op.execute('DROP SCHEMA IF EXISTS files CASCADE')
    op.execute('DROP SCHEMA IF EXISTS analysis CASCADE')